# Generated by Django 3.1.6 on 2021-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210219_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='Changing-default-category.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='subcategorydefault.jpg', null=True, upload_to=''),
        ),
    ]
