# Generated by Django 3.1.6 on 2021-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210219_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
